
. 结构化分析方法 - 功能模型
. 结构化设计方法 -


[plantuml]
....
@startuml

结构化分析方法 as a

结构化设计方法 as b

(系统功能模型) as c

(系统总体设计) as d

(详细设计) as e

详细设计工具 as f

a --> c

c --> d

b -> d

d --> e

f -left-> e


@enduml
....


* 表达问题域信息的基本术语
* 表达功能模型的的工具-DFD图
* 数据结构符和判定表/判定树
* 变换型数据流图和事务型数据流图
* 模块，模块内聚与耦合
* 详细设计工具： 框图/PAD图/N-S图/伪码

* 构建系统功能模型的步骤
**

---

. 问题空间的理解

. 协作

. 变化
.. 用户
.. 竞品
.. 协调人
.. 审批, 约束需求
.. 技术


### 基本术语

* 数据流
* 加工
* 数据存储
* 数据源/数据潭
** 起点与终点



[plantuml]
....
@startuml
title Dataflow Diagram

(预订机票) as a
(准备机票) as b
(记账) as c
[旅客] as d

[旅行社] ->  a : 订票单

a -> b : 航班

a --> c  : 费用

c -> d : 账单

b --> d : 机票

[航班] ..> a

c <..> [记账文件]

@enduml
....

== 总体设计步骤

[plantuml]
....

[DFD] --> [MSD]

[变换型数据流] as a

[事务型数据流] as b

[MSD] ..> a

note left of a
主模块，
输入模块，
    输入模块
    变换模块
输出模块，
    变换模块
    输出模块
转换模块
end note

[MSD] ..> b

a --> (变换设计)

b --> (事务设计)

a . (复审)
(复审) .> (确定边界)

(确定边界) ..> a

....

=== 模块化及启发式规则

. 模块是执行一个特殊任务的一个过程以及相关的数据结构
.. 接口
.. 实现
. 结构化软件是一个典型的模块化方法
.. 模块的关系
... 引用
... 数据传递, `_A为了完成功能， 向B传数据， 则认为B依赖A_`
... 控制
.. 模块的耦合
... 内容
... 公共：如多个模块引用公共数据
... 控制／标记／数据
.. 内聚 -- 偶然／逻辑／时间／过程／通信／顺序／功能／
. 规则
.. 改进
.. 模块规模适中
.. 深度／扇入／扇出
.. 作用域与控制域的协调
.. 降低接口复杂度


=== 结构化程序设计

. 顺序
. if
. loop


.详细设计工具
|===
|Header 1 |Header 2 |Header 3

|程序流程图
|-
|过早考虑细节，　拆分不好拆分

|盒图
|自顶向下，　一步一步求精
|-

|PAD图
|-
|-

|PDL
|伪代码
|-

|===


==== 结构化程序设计方法学

==== 各种逻辑式程序设计方法学

==== 函数式程序设计方法学

==== 面向对象程序设计方法学



















